### ISSUE TITLE
KeyError: 'Ref is not available in versioning.'

### ISSUE THREAD

**Issue by husnadrs** [tudelft3d/cityjson-versioning-prototype#10]
Hi,

I am trying to do the tutorial Cityjson versioning prototype (https://github.com/tudelft3d/cityjson-versioning-prototype.git) using the dummy and rotterdam data but when come to 3rd step (Add the version with the moved roof in master:),  the KeyError: 'Ref is not available in versioning.' come out, so i can't proceed it, below the error that come out in my screen

Traceback (most recent call last):
  File "C:\Users\Husnadrs\Desktop\proj2\Scripts\cjv-script.py", line 33, in <module>
    sys.exit(load_entry_point('cjv==0.1', 'console_scripts', 'cjv')())
  File "C:\Users\Husnadrs\Desktop\proj2\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Husnadrs\Desktop\proj2\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Husnadrs\Desktop\proj2\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Husnadrs\Desktop\proj2\lib\site-packages\click\core.py", line 1626, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "C:\Users\Husnadrs\Desktop\proj2\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Husnadrs\Desktop\proj2\Scripts\cjv.py", line 58, in process_pipeline
    processor(citymodel)
  File "C:\Users\Husnadrs\Desktop\proj2\Scripts\cjv.py", line 142, in processor
    command.execute()
  File "C:\Users\Husnadrs\Desktop\proj2\Scripts\commands.py", line 211, in execute
    parent_versionid = vcm.versioning.resolve_ref(self._ref)
  File "C:\Users\Husnadrs\Desktop\proj2\Scripts\cityjson\versioning.py", line 100, in resolve_ref
    raise KeyError("Ref is not available in versioning.")
KeyError: 'Ref is not available in versioning.'

Am I missing any steps or anything need to looking in CityJSON encoding??

**Comment by liberostelios** [comment]
Hey @husnadrs,

Thanks so much for reporting!

I think that your problem probably occurs on the 4th step, rather than the 3rd right? I realized that the 2nd step, actually, fails to create the branch and, therefore, when you are trying to commit on it you get this error message (which isn't very helpful either). I'll push a fix for both the `branch` command and improve the issue and will let you know.

**Comment by husnadrs** [comment]
Thank you for you response,

I'm looking forward to hearing from you about the issues. In the meantime, is there any alternative tool to done cityjson versioning?

**Comment by liberostelios** [comment]
I've pushed a fix to the issue (also improved the message a bit). I hope this is clear enough. I've also updated the wrong name of default branch (now `main`) in the readme, so hopefully you won't stumble across this issue as well.

Hopefully, that's enough to resolve your issue. Otherwise, let me know if anything else is not working properly, please.

**Comment by husnadrs** [comment]
Hi,

I've try again the tutorial but the same keyerror on the 4th step (Add the version with the deleted building in test-branch), It seem cannot be add any version in the branch, below my full step that i 've done from 1st till 4th step, hope you can consider this issue 


(proj2) (base) C:\Users\Husnadrs\Desktop\proj2\Scripts>cjv init commit "C:\Users\Husnadrs\Desktop\proj2\Scripts\rotterdam\initial.json" -m "Initial commit" -o rotterdam.json
Provide your name: jj
Appending vertices...
Removing duplicate vertices...
Updating main to 2d4dea00086df28b12d17276f140029e2a6e500d
Saving rotterdam.json...

(proj2) (base) C:\Users\Husnadrs\Desktop\proj2\Scripts>cjv rotterdam.json branch test-branch
The following branches are available:
- main

(proj2) (base) C:\Users\Husnadrs\Desktop\proj2\Scripts>cjv rotterdam.json commit "C:\Users\Husnadrs\Desktop\proj2\Scripts\rotterdam\initial_moved_roof.json" -m "Move a building's roof"
Provide your name: jj
Appending vertices...
Removing duplicate vertices...

Changes:

        changed: {CCF7B5DE-ADF6-4754-B670-8187225E0758} (0440325579f85b0.. -> b3da74cd8557877..)

852 objects not changed.

Updating main to 374a6a575feda80abefabee7e3f9f8f84182917c
Saving rotterdam.json...

(proj2) (base) C:\Users\Husnadrs\Desktop\proj2\Scripts>cjv rotterdam.json commit "C:\Users\Husnadrs\Desktop\proj2\Scripts\rotterdam\initial_deleted_building.json" test-branch -m "Delete a building"
Provide your name: jj
Traceback (most recent call last):
  File "C:\Users\Husnadrs\Desktop\proj2\Scripts\cjv-script.py", line 33, in <module>
    sys.exit(load_entry_point('cjv==0.1', 'console_scripts', 'cjv')())
  File "C:\Users\Husnadrs\Desktop\proj2\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Husnadrs\Desktop\proj2\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Husnadrs\Desktop\proj2\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Husnadrs\Desktop\proj2\lib\site-packages\click\core.py", line 1626, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "C:\Users\Husnadrs\Desktop\proj2\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Husnadrs\Desktop\proj2\Scripts\cjv.py", line 58, in process_pipeline
    processor(citymodel)
  File "C:\Users\Husnadrs\Desktop\proj2\Scripts\cjv.py", line 142, in processor
    command.execute()
  File "C:\Users\Husnadrs\Desktop\proj2\Scripts\commands.py", line 211, in execute
    parent_versionid = vcm.versioning.resolve_ref(self._ref)
  File "C:\Users\Husnadrs\Desktop\proj2\Scripts\cityjson\versioning.py", line 100, in resolve_ref
    raise KeyError("Ref is not available in versioning.")
KeyError: 'Ref is not available in versioning.'

(proj2) (base) C:\Users\Husnadrs\Desktop\proj2\Scripts>cjv rotterdam.json log main test-branch --graph
Found 2 versions.

Traceback (most recent call last):
  File "C:\Users\Husnadrs\Desktop\proj2\Scripts\cjv-script.py", line 33, in <module>
    sys.exit(load_entry_point('cjv==0.1', 'console_scripts', 'cjv')())
  File "C:\Users\Husnadrs\Desktop\proj2\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Husnadrs\Desktop\proj2\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Husnadrs\Desktop\proj2\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Husnadrs\Desktop\proj2\lib\site-packages\click\core.py", line 1626, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "C:\Users\Husnadrs\Desktop\proj2\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Husnadrs\Desktop\proj2\Scripts\cjv.py", line 58, in process_pipeline
    processor(citymodel)
  File "C:\Users\Husnadrs\Desktop\proj2\Scripts\cjv.py", line 72, in processor
    command.execute()
  File "C:\Users\Husnadrs\Desktop\proj2\Scripts\commands.py", line 46, in execute
    history.add_versions(self._citymodel.versioning.resolve_ref(ref))
  File "C:\Users\Husnadrs\Desktop\proj2\Scripts\cityjson\versioning.py", line 100, in resolve_ref
    raise KeyError("Ref is not available in versioning.")
KeyError: 'Ref is not available in versioning.'


Thank you.

**Comment by liberostelios** [comment]
I just checked and this issue must have been fixed. You need to pull the latest changes and run the second command again: `cjv rotterdam.json branch test-branch`. Did you do that?
